# Generated by Django 5.0.3 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_payment_status_payment_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма платежа'),
        ),
    ]
